all:
	g++ lista_linear_ordenada.cpp --std=c++11 -g -o lista_linear_ordenada
	g++ lista_simples.cpp --std=c++11 -g -o lista_simples
	g++ lista_ordenada.cpp --std=c++11 -g -o lista_ordenada
	g++ lista_benchmark.cpp --std=c++11 -g -o lista_benchmark
	
clean:
	rm lista_linear_ordenada -rf
	rm lista_simples -rf
	rm lista_ordenada -rf
	rm lista_benchmark -rf
	rm *~ -rf